export function getRandomText(
  level: "normal" | "expert" | "master" = "normal"
): string {
  const texts = {
    normal: [
      `The morning sun filtered gently through the thin curtains, casting long, warm beams across the wooden floor. Birds chirped happily outside the window, each melody blending seamlessly with the rustling of the leaves. The smell of freshly baked bread from the nearby bakery drifted into the room, mingling with the faint scent of morning dew from the garden. A cat stretched lazily across the windowsill, its fur shimmering in the sunlight, while the distant sound of children playing in the street brought a sense of calm and contentment. It was one of those mornings when everything felt peaceful, simple, and perfectly ordinary, yet full of tiny, beautiful moments that made life feel cozy and welcoming.`,
      `A gentle breeze swept across the sprawling garden, carrying with it the sweet aroma of blooming roses, lavender, and jasmine. The leaves of the tall oak trees swayed lightly, creating a soothing whisper that mingled with the distant hum of bees collecting nectar. On the stone path, a small group of children laughed and chased each other, their bright voices echoing through the quiet morning. Nearby, a wooden bench sat under a cherry blossom tree, its petals slowly drifting to the ground, adding splashes of pink to the green grass. Every corner of the garden seemed alive with gentle motion, colors, and soft sounds that made the world feel vibrant yet calm.`,
      `The small wooden boat floated silently on the lake, barely disturbing the mirrored surface that reflected the pastel colors of the evening sky. Water lilies dotted the edges of the lake, their delicate petals opening to the last rays of the sun. In the distance, a fisherman quietly adjusted his line, the faint sound of the water lapping against the shore blending with the call of a distant loon. As the sun sank further, streaks of gold and orange lit the clouds, creating a serene canvas that seemed to hold the entire world in a moment of perfect stillness and beauty. The soft sounds, the gentle air, and the fading light combined to create a peaceful atmosphere unlike any other.`,
      `Children played in the park, running across the grass and laughing as their kites danced in the wind. The scent of fresh-cut grass and flowers filled the air, while the distant sound of a fountain splashing added a soothing rhythm. A family gathered under the shade of a large tree, enjoying a picnic with sandwiches, fruits, and lemonade. Dogs barked joyfully as they chased after balls thrown by their owners. Every sound, every color, every movement combined to make the afternoon feel alive and full of happiness.`,
      `The bakery on the corner opened its doors, revealing shelves lined with golden pastries, cakes, and breads. The scent of cinnamon, chocolate, and freshly baked goods wrapped around the customers, making each visit feel like a warm embrace. A young woman carefully selected a loaf of bread, while a child eagerly pointed to a chocolate croissant. Outside, the morning sun shone softly on the cobblestone streets, casting a warm glow on the scene. The world seemed peaceful, happy, and perfectly ordinary in its small moments of charm.`,
      `A cat lounged on the windowsill, stretching lazily as it basked in the soft sunlight. Outside, trees swayed gently in the breeze, and birds chirped melodiously from the branches. A small pond reflected the sky, mirroring clouds that drifted lazily above. The quiet hum of life carried on in the garden, as insects buzzed around flowers and leaves rustled softly. Everything felt calm, steady, and reassuring, as if time itself had slowed for just a moment.`,
      `The scent of rain filled the air as a light drizzle began to fall over the city. People hurried along the sidewalks with umbrellas, leaving small puddles on the pavement as they went. Streetlights reflected on the wet surfaces, creating tiny pools of glowing color. Children splashed happily in puddles, laughing as the water sprayed around them. The combination of rain, laughter, and urban life made the city feel alive, vibrant, and full of simple joy.`,
      `A quiet street stretched out under the evening sky, lined with tall oak trees whose leaves rustled gently in the wind. Lamps cast soft pools of light on the cobblestones, illuminating small details like a stray cat moving silently, or a couple walking hand in hand. The air was cool and fresh, carrying scents from nearby bakeries and cafes. Every sound, movement, and shadow seemed to tell a story, as if the street itself were alive and breathing.`,
      `The river wound gently through the countryside, reflecting the soft hues of the sunset. Fish leapt occasionally from the water, creating small ripples that shimmered in gold and pink. On the banks, wildflowers swayed with the breeze, and the distant hum of insects filled the quiet air. A small boat drifted lazily, its wooden sides creaking softly. Nature seemed to exist in perfect harmony, inviting anyone nearby to pause and simply watch, listen, and breathe.`,
      `The smell of fresh coffee and baked goods filled the cozy cafe as people chatted quietly at small tables. Sunlight streamed through large windows, illuminating the rich colors of pastries and the warm tones of the wooden furniture. A young man read a newspaper, while a woman typed quickly on her laptop. Outside, the world moved on, but inside the cafe, everything felt calm, comfortable, and perfectly ordinary in its quiet rhythm.`,
    ],

    expert: [
      `The city streets shimmered with reflections from neon lights, slick from an earlier rain, while the faint scent of roasted chestnuts and coffee drifted through the air. People hurried past, umbrellas in hand, their footsteps echoing softly against the cobblestones as a distant street musician played a melancholy tune on his violin. High above, the windows of the towering buildings glowed warmly, revealing glimpses of life inside each apartment: families dining together, a solitary figure reading by the lamp, a couple sharing quiet laughter. The evening was alive yet calm, a complex mix of movement, light, and sound that painted the city with both energy and serenity. Each moment held a detail, a microcosm of urban life, that drew the observer into the subtle poetry of the everyday.`,
      `Beneath the towering redwoods, the forest was a cathedral of nature, with sunlight filtering through the dense canopy, illuminating patches of moss and ferns in a soft green glow. The air smelled earthy and fresh, filled with the subtle aroma of damp bark and decomposing leaves. Birds called from unseen branches, their songs harmonizing with the gentle babbling of a nearby stream. Every so often, a squirrel darted across the forest floor, disappearing behind a tree trunk with practiced agility. Walking through the woods felt like stepping into another world, one that had existed for centuries, untouched and magnificent, inviting contemplation and quiet awe at the vastness and beauty of life in its rawest form.`,
      `In a small, cozy bakery tucked into a corner of the bustling town, the scent of cinnamon, chocolate, and freshly baked bread enveloped everyone who entered. The shelves were lined with golden-brown croissants, delicate pastries, and loaves of bread with perfectly crisp crusts. Behind the counter, the baker moved with practiced grace, shaping dough, sprinkling sugar, and chatting warmly with regular customers. Outside, the streets were alive with morning traffic, children heading to school, and shopkeepers preparing for the day. Yet inside, everything felt calm, comforting, and almost timeless, a sanctuary of warmth and aroma amidst the noise and rush of everyday life.`,
      `The old library stood as a silent guardian of knowledge, its towering shelves filled with leather-bound volumes that whispered stories of centuries past. The scent of aged paper and ink mingled with the faint aroma of polished wood, creating an atmosphere thick with history and wisdom. Sunlight filtered through stained glass windows, casting colorful patterns on the worn wooden floors. A solitary figure sat at a large oak table, engrossed in a dusty tome, while the soft rustle of pages turning echoed through the quiet halls. Every corner of the library seemed to hold a secret, a story waiting to be discovered by those willing to listen and learn from the echoes of time.`,
      `The bustling marketplace was a vibrant tapestry of colors, sounds, and scents, where merchants called out their wares and customers haggled for the best prices. Stalls overflowed with fresh produce, fragrant spices, handmade crafts, and exotic textiles, each item telling a story of distant lands and skilled artisans. The air was alive with the mingling aromas of grilled meats, sweet pastries, and earthy herbs, while the chatter of bargaining voices created a lively soundtrack to the scene. Children weaved through the crowd, their laughter ringing out as they chased one another around carts and displays. Amidst the chaos, there was a sense of community and connection, a shared experience that brought people together in the heart of the marketplace.`,
      `The serene lake mirrored the sky above, its surface a perfect canvas for the soft hues of dawn. Mist rose gently from the water, swirling in delicate tendrils that caught the first light of day, creating an ethereal glow. Along the shore, reeds swayed in the light breeze, their tips glistening with dew. A lone fisherman sat quietly in his boat, casting his line with practiced ease, while a family of ducks glided gracefully across the water, leaving gentle ripples in their wake. The world felt hushed and still, as if time itself had paused to savor the beauty of the moment, inviting anyone present to breathe deeply and absorb the tranquility that surrounded them.`,
      `The quaint village was nestled in a valley, surrounded by rolling hills and lush meadows that stretched as far as the eye could see. Cobblestone streets wound through rows of charming cottages, each adorned with colorful flower boxes and ivy-covered walls. The scent of freshly baked bread wafted from the bakery, mingling with the earthy aroma of rain-soaked soil after a brief afternoon shower. Villagers went about their daily routines, greeting one another with warm smiles and friendly waves. Children played in the village square, their laughter echoing off the stone buildings, while elders sat on benches, sharing stories of days gone by. The village exuded a timeless charm, a place where life moved at a gentle pace and community thrived in every interaction.`,
      `The coastal town was alive with the sounds of seagulls calling overhead and waves crashing against the rocky shore. Salt air filled the lungs, carrying with it the scent of seaweed and fresh fish from the bustling harbor. Fishermen worked diligently, mending nets and unloading their catch, while colorful boats bobbed gently in the water. Along the boardwalk, tourists strolled leisurely, stopping to admire the quaint shops and cafes that lined the street. The sun cast a golden glow over the scene, illuminating the vibrant colors of the buildings and the sparkling surface of the ocean. It was a place where the rhythm of life was dictated by the tides, and every moment felt infused with the energy and beauty of the sea.`,
      `The mountain trail wound its way through dense pine forests, the scent of evergreen needles and fresh earth filling the crisp air. Sunlight filtered through the tall trees, casting dappled shadows on the rocky path. The distant sound of a waterfall echoed softly, mingling with the occasional chirp of birds and rustle of small animals in the underbrush. Hikers moved steadily along the trail, their breaths visible in the cool mountain air, pausing occasionally to take in breathtaking views of the valley below. Each step brought a sense of adventure and connection to the natural world, a reminder of the vastness and beauty that lay beyond the familiar.`,
      `In the heart of the bustling city park, a symphony of life unfolded beneath the canopy of ancient trees. The laughter of children playing tag intertwined with the rhythmic clatter of joggers' footsteps on gravel paths. Couples strolled hand in hand along winding walkways lined with vibrant flowerbeds, while artists set up easels to capture the scene in vivid watercolors. The scent of blooming roses mingled with the earthy aroma of freshly cut grass, creating an intoxicating blend that filled the air. Nearby, a street performer played a soulful tune on his saxophone, the notes weaving through the ambient sounds of nature and human activity. The park was a living tapestry of movement, color, and sound, a sanctuary where the city's pulse slowed just enough to appreciate the simple joys of life.`,
    ],

    master: [
      `Beyond the ancient marketplace, the sprawling city stretched as far as the eye could see, with narrow winding streets, towering stone buildings, and rooftops that glittered under the golden glow of the setting sun. Merchants called to passersby, peddling exotic spices, silks, and trinkets, while the distant sound of bells echoed from the cathedral in the city center. Each corner of the city was alive with stories: a painter capturing the sunlight on canvas, a scholar hurriedly reading in a quiet courtyard, a musician strumming a delicate melody for spare coins. The air was thick with scents, sounds, and colors that blended into an overwhelming symphony, demanding attention and leaving an indelible impression upon anyone wandering through the labyrinthine streets. The history of the city, centuries in the making, seemed tangible in every stone, every shadow, and every whisper of wind that carried tales from long ago.`,
      `In the dimly lit study of an old mansion, shelves upon shelves of books towered toward the ceiling, filled with manuscripts and tomes that held the accumulated knowledge of countless generations. The smell of aged paper and ink mingled with the faint scent of burning wood from the fireplace, creating an atmosphere of solemnity and contemplation. Outside, the wind howled through the leafless trees, rattling the windows and causing shadows to dance across the floor. A single candle flickered on the desk where a scholar hunched over an open book, tracing intricate diagrams and making careful notes, each movement deliberate and precise. The room seemed suspended in time, a sanctuary of learning and thought, where the weight of history and discovery could almost be felt pressing in on every side.`,
      `Beneath the night sky, vast and star-filled, the wilderness stretched endlessly, broken only by the occasional silhouette of a mountain or the glint of a river reflecting the moonlight. Campers huddled around a crackling fire, sharing stories that spanned generations, their faces illuminated by warm orange light. The air was crisp and carried the scent of pine, damp earth, and smoke from the fire. Every rustle in the underbrush, every distant hoot of an owl, added to the sensation that the forest was alive, ancient, and watching. Time seemed to slow, allowing the mind to wander across memories, imagination, and the very fabric of existence itself, leaving the campers with a profound sense of awe, wonder, and humility in the face of nature's vastness.`,
      `The labyrinthine corridors of the ancient castle twisted and turned unpredictably, each chamber adorned with tapestries depicting heroic battles, mystical beasts, and the rise and fall of empires long forgotten. The scent of aged stone, burning torches, and old wood filled the air, mingling with the faint aroma of herbs stored in clay jars on dusty shelves. Echoes of footsteps reverberated through the halls as a lone figure navigated the maze-like structure, their torchlight casting flickering shadows that danced across the walls. Every corner held a secret: hidden doors, forgotten passageways, and relics of a bygone era that whispered stories of intrigue, valor, and mystery to those willing to listen. The castle was not merely a building but a living testament to history, its very walls imbued with the essence of countless lives and events that had shaped its existence over centuries.`,
      `As the orchestra began its symphony, the grand hall came alive with the soaring violins and resonant cellos, guiding the audience through waves of emotion that rose and fell like the tides of an endless sea. The conductor moved with passionate intensity, his baton weaving intricate patterns in the air as he coaxed every nuance from the musicians. The scent of polished wood and aged paper from the music sheets mingled with the faint aroma of perfume and cologne from the elegantly dressed attendees. Each note seemed to carry a story, a fragment of human experience that transcended language and culture, uniting everyone present in a shared journey of sound and feeling. The performance was not merely a concert but a profound exploration of the depths of emotion, artistry, and the human spirit itself.`,
      `In the shadow of the crumbling cathedral, the old clock tower loomed, its bells echoing through the empty streets while ivy crept across centuries-old stone, bearing silent witness to the passage of countless generations. The air was thick with the scent of damp stone, moss, and forgotten memories, as if the very walls held the weight of history within their cracks and crevices. A solitary figure stood at the base of the tower, gazing up at the intricate carvings that adorned its facade, each one telling a story of faith, power, and human endeavor. The wind whispered through the deserted streets, carrying with it echoes of long-gone voices and footsteps, creating an eerie yet captivating atmosphere that invited reflection on the impermanence of life and the enduring legacy of those who came before.`,
      `The labyrinthine corridors of the ancient castle twisted and turned unpredictably, each chamber adorned with tapestries depicting heroic battles, mystical beasts, and the rise and fall of empires long forgotten. The scent of aged stone, burning torches, and old wood filled the air, mingling with the faint aroma of herbs stored in clay jars on dusty shelves. Echoes of footsteps reverberated through the halls as a lone figure navigated the maze-like structure, their torchlight casting flickering shadows that danced across the walls. Every corner held a secret: hidden doors, forgotten passageways, and relics of a bygone era that whispered stories of intrigue, valor, and mystery to those willing to listen. The castle was not merely a building but a living testament to history, its very walls imbued with the essence of countless lives and events that had shaped its existence over centuries.`,
      `Above the desert dunes, the setting sun ignited the sky in a blaze of crimson and gold, casting elongated shadows over the sands while the distant call of a hawk echoed across the barren landscape. The air was thick with the scent of dry earth, warm sand, and the faint aroma of desert blooms that thrived against all odds. A solitary traveler moved steadily across the dunes, their silhouette etched sharply against the vibrant horizon, each step leaving a fleeting imprint on the shifting sands. The vastness of the desert stretched endlessly in every direction, a testament to nature's raw power and beauty, inviting contemplation on solitude, resilience, and the timeless dance between light and shadow.`,
      `In the dimly lit study, shelves overflowed with manuscripts, some detailing alchemical experiments, others recounting journeys through perilous lands, and the faint scent of parchment and ink hung in the air like a tangible memory. A large wooden desk sat cluttered with quills, ink pots, and
  open books, their pages filled with intricate diagrams and cryptic notes. The flickering light of a single candle cast long shadows across the room, illuminating the face of a scholar deep in thought, his eyes scanning the text with intense focus. Outside, the wind howled through the trees, rattling the windows and adding a haunting soundtrack to the scene. The study felt like a sanctuary of knowledge and discovery, a place where time stood still and the pursuit of understanding reigned supreme.`,
    ],
  };

  const selected = texts[level];
  return selected[Math.floor(Math.random() * selected.length)];
}
